name: Build Docker Image

on:
  push:
    branches:
      - master

env:
  REGISTRY_PATH: cr.yandex/crptqdm2r1qrasr6n9vm/mayak-mubeng

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: auth in yandex registry
      env:
        YC_DOCKER_PUSH: ${{ secrets.YC_DOCKER_PUSH }}
      run: echo "${YC_DOCKER_PUSH}" | docker login --username json_key --password-stdin cr.yandex

    - name: Pull docker image from registry (for cache)
      run: docker pull "${REGISTRY_PATH}:latest" || true # don't crash on the first run

    - name: Build the Docker image
      run: docker build --cache-from "${REGISTRY_PATH}:latest" --tag "${REGISTRY_PATH}:${GITHUB_SHA}" --tag "${REGISTRY_PATH}:latest" .

    - name: Push docker image to registry
      run: docker push "${REGISTRY_PATH}:${GITHUB_SHA}"
    - run: docker push "${REGISTRY_PATH}:latest"
    
 deploy:
   runs-on: ubuntu-latest
   needs: build
   env:
     DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
     DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

   steps:
   - uses: actions/checkout@v2
   - name: Create private SSH key
     run: echo "${DEPLOY_KEY}" > id_rsa && chmod 0600 id_rsa

   - name: Remote pull of docker images on $DEPLOY_HOST
     run: ssh -o "StrictHostKeyChecking no" -i id_rsa "${DEPLOY_HOST}" "sudo docker-compose -f ~/mubeng/docker-compose.yml pull"
   - name: Restart serices on $DEPLOY_HOST
     run: ssh -o "StrictHostKeyChecking no" -i id_rsa "${DEPLOY_HOST}" "sudo docker-compose -f ~/mubeng/docker-compose.yml up -d"

   - name: Cleanup stopped containers on $DEPLOY_HOST
     run: ssh -o "StrictHostKeyChecking no" -i id_rsa "${DEPLOY_HOST}" "sudo docker container prune --force --filter \"until=$(date +'%Y-%m-%dT%H:%M:%S' --date='-2 days')\""
   - name: Cleanup untagged images older than 7 days on $DEPLOY_HOST
     run: ssh -o "StrictHostKeyChecking no" -i id_rsa "${DEPLOY_HOST}" "sudo docker image prune --force --filter \"until=$(date +'%Y-%m-%dT%H:%M:%S' --date='-7 days')\""
